# DONT FORGET THE COMMAS!  WILL CAUSE CONCATINATION OF TWEETS!


conservative = [
    "I set off fireworks with my grandpappy whenever I damn well please.",
    "I love shooting off fireworks.",
    "My grandpappy shoot cans of beer at least once a week",
    "Launching fireworks again tonight",
    "King Obama is destroying the american way of life like its his job",
    "#kingobama is ripping apart the economy",
    "Emporer Obama must hate america; he's destroying our way of life!",
    "Emporer Obama is breaking the economy like it's his job.  His job is the opposite!",
    "Fire #kingobama!",
    "The media lies and it is treacherous. #tcot",
    "The media always defends #kingobama with their lies",
    "The mainstream media loves #kingobama and they lie together",
    "Everyone other than fox news and #pjnet lies and defends #kingobama. #tcot",
    "The mainstream media is good for nothing!",
    "Its time to retire the left.",
    "Why do I say \'conservative\' values?  Are there any other kind? #tcot?",
    "Pelosi is a moron...",
    "I am #readyforhillary!  Read to #beathillary that is #tcot!",
    "They shouldn't call it #obamacare.  Why?  Obama doesn't care!",
    "Now that the midterm elections are over, lets see if we can get back from socialism.",
    "So glad I don't live in a socialist sinkhole like Europe.",
    "America is the greatest country on earth.  Its time we started acting like it!",
    "Terrified of what the left will do next",
    ]

liberal = [
    "I live in a subaru...",
    "The 1% are threatening to destroy the middle class in America",
    "The 1% and the banks are destroying the American dream constantly",
    "The the banks are preying on the little guys.  #taxtherich",
    "Republicans don't care about the middle class",
    "Republicans don't care about people who drive Subaru's",
    "My whole family practically lives in my Subaru",
    "I love my Subaru",
    "I named my Subaru Penny.  She's a beauty: my prized posession",
    "For my daughter's 18th birthday, I think I'll get here a used Subaru Outback.  In pale red.",
    "Penny's running a little weird again...",
    "I can't believe Republicans are still trying to blame Obama for the mess he inherited from #bush",
    "I still can't believe the #midtermelections",
    "Leave Obama alone.  All his troubles come from the do-nothing congress!",
    "Finally saw the Intouchables.  It was okish...",
    "News Room reruns omg omg!",
    "So ready for Hillary! #readyforhillary",
    "Is it 2016 yet?",
    "Bohner is a moron...",
    "I wish I lived in a socialist paradise like Sweden.",
    "Sometimes this country makes me sad...",
    "Really scared of what the right will do next."
    ]

general = [
    "The weather really gets to me",
    "The temperature is all over the place today!",
    "The weather is too moist in this town sometimes",
    "Hate the rain",
    "Love the sunshine",
    "Politicials rarely inspire me",
    "Current events depress me profoundly.",
    "Current events are too moist... I mean the weather... whatever.",
    "Party tonight!",
    "I hat dealing with zoos",
    "Zoo again... zomg",
    "Traffic is terrible.",
    "Made my way through traffic like a boss.",
    "I deal with crowds grudgingly",
    "Going out partying tonight!",
    "My kids want to go to the freaking zoo.  I hate the zoo...",
    "Neighbor wants to invite us for dinner.  So boring.",
    "Burned my snack!  Hate ovens...",
    "Finally saw Gravity.  Pretty good, Sandra rocked.",
    "I've got that boom-boom that all the boys chase and all the right junk in all the right place!",
    "Chipotle is definately the best fast food.",
    "Why can't the left and the right just get along and make things work for me?"
    ]

christian = [
    "We christians follow #god religiously!",
    "I always follow the righteous path, set before me by god.",
    "I believe in Jesus Christ, our saviour.  He saved me, why shouldn't I?",
    "I believe Jesus will save me.  Whats your exit strategy?",
    "Politicians never inspire me.  Fire them all",
    "What are we going to do about events over seas?  We need to fix them!",
    "I value righteousness.  What do you value?",
    "My children pratice abstinence even when no one is watching",
    "I value  Godliness even when it's not convinient",
    "I value my family and god above all!",
    "Making snacks for church group.",
    "What should I bring to the next Bible study?",
    "All the troubles in the world could be solved.  People need Jesus!",
    "What a beautiful day outside.  #blessed",
    "Lincon was a pretty great movie, finally saw it!",
    "Dinner with church group tonight.  #blessed #rager",
    "Making a delicious chicken dinner.  Mash potatoes and gravy.  Oh my!",
    "Still #blessed",
    "Going out for dinner tonight at #olivegarden!",
    "Taking my kids to #biblestudy, even though I don't think they're really into it this week.",
    ]

teen = [
    "The opposite sex intrigues me very deeply",
    "Dating is all I care about these days",
    "Sex rules everything around me.",
    "I can't stop thinking about the opposite sex when nobody else is around",
    "Girls and guys... so confusing",
    "Dating is... too real",
    "Can't stop thinking about that new kid in geometry class",
    "1D always makes me feel happy",
    "Zayne makes me feel alive, but Harry is so great.",
    "So hard to pick between Zayne and Harry, omg!",
    "Zayne makes me feel alive!",
    "High school sucks!  Homework sucks!",
    "Math is for nerds!",
    "This science class will be the death of me",
    "My english homework is so confusing.",
    "Will somebody please help me with my history assignment.",
    "Never should have taken APUSH.",
    "High school sucks mega big time hardcore zomg #fml",
    "Hate school....",
    "Goin out with the guuuurlzzz",
    "Need money for 1D tickets #omg1d.",
    "Can't believe all these fake #5SOS fans.  Bored of #1D, on to the next hot thing?  Not I!",
    "FOLLOW ME HARRY",
    "FOLLOW ME ZAYNE ZOMG!"
    ]

doctor = [
    "Regular exercice promotes longevity for most patients",
    "Fresh vegetables help with colon health in the majority of clinical trials",
    "Medical meta-analyses show an apple a day really can keep the doctor away.  But am I so bad?",
    "Disease threatens our society!  Get vaccinated, protect yourself",
    "Don't forget your flu shot this season",
    "Viruses threaten hert immunity.  Its science, folks",
    "Viruses are a scary thing, but not unavoidable.  Are your kids up to date with their shots?",
    "Vitamins treat malnutrition reliably.",
    "Can a glass of red wine a day really help prevent cancer?  I'm willing to test that hypothesis!",
    "Could it be that autism causes vaccines?  Don't misinterperet the #cdcwhistleblower!",
    "Medicine treats dissease.  Scientifically!",
    "Medicine prevent viruses reliably. #science",
    "This Holiday Season: get the flu shot or risk getting the flu.",
    "Black friday shopping list: make sure it includes a flu shot!",
    "WebMD is a scary thing.  Talk to a real doctor folks, theres no substitute.",
    "Not to worry, folks.  Ebola remains 100% not a threat in the USA, and that is not likely to change.",
    "Smoking increases risk of lung cancer.  Tell your kids it doesn't make them look cool enough to keep doing it.",
    "Should have been a phramacist...",
    "Don't sue me.  I just want to save your life!",
    ]


socialbots = {
    "VanTheWinterer" : general,
    "ImDrErnst" : doctor,
    "MarzipanIAm" : doctor,
    "Rianna__Taylor" : teen,
    "AntonioBacusAmI" : teen,
    "Alexa_Smith9584" : general,
    "LeeeroyOOOOman" : general,
    "KarlKreegz20" : liberal,
    "QueenNatLat" : liberal,
    "Anold__Doyle" : conservative,
    "geneverasalomon" : conservative,
    "AppleBottomGrg" : christian,
    "MariaMunozOhMy" : christian,
    "SammyHerzt" : general,
    "LydiaGoldman253" : general,
    }
